### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by Kevin-Chen0** [stkubr/MAML#1]
This is despite I have did:  pip install Crypto.

I have double checked my site packages to ensure that it is there. 

I also tried the following suggestion to change the site-package folder name from crypto to Crypto:https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher

But it then does not recognize import Random.

Do we have to import pycrypto instead?

EDIT: I think I solved but needs further test. Since I am using Python 3.6.7, I need to install pycryptodome rather than pycrypto or Crypto.

https://stackoverflow.com/questions/41813030/problems-with-installation-pycrypto-in-python-3-6

**Comment by stkubr** [comment]
Yep, thanks, it should be `sudo pip install pycrypto`
